/** @type {import('tailwindcss').Config} */
// Design tokens copied verbatim from the Stitch "Modern Trust Finance" design system.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  safelist: [
    // dynamically composed status colors (icons/badges/borders built at runtime)
    ...['secondary', 'harvest', 'warning', 'tertiary', 'error', 'on-secondary-container'].flatMap((c) => [
      `bg-${c}/10`, `bg-${c}/5`, `text-${c}`, `border-${c}/30`, `border-${c}/40`,
    ]),
    'bg-on-surface-variant/10', 'text-on-surface-variant',
    'bg-surface-container-high',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#565e74',
        'on-tertiary-fixed': '#001a42',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'on-secondary-container': '#00714d',
        'on-tertiary': '#ffffff',
        secondary: '#006c49',
        'surface-container-highest': '#d3e4fe',
        'inverse-surface': '#213145',
        'surface-container-high': '#dce9ff',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary-container': '#3980f4',
        surface: '#f8f9ff',
        'on-secondary-fixed-variant': '#005236',
        error: '#ba1a1a',
        'surface-container-low': '#eff4ff',
        'on-tertiary-fixed-variant': '#004395',
        'on-primary-fixed-variant': '#3f465c',
        tertiary: '#3980f4',
        'on-surface-variant': '#45464d',
        'on-secondary': '#ffffff',
        'primary-fixed': '#dae2fd',
        'secondary-fixed': '#6ffbbe',
        background: '#f8f9ff',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#131b2e',
        'on-secondary-fixed': '#002113',
        'on-surface': '#0b1c30',
        'tertiary-fixed-dim': '#adc6ff',
        'inverse-on-surface': '#eaf1ff',
        'surface-container': '#e5eeff',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#6cf8bb',
        'on-error': '#ffffff',
        'on-primary-fixed': '#131b2e',
        primary: '#131b2e',
        'outline-variant': '#c6c6cd',
        'tertiary-container': '#001a42',
        'tertiary-fixed': '#d8e2ff',
        'surface-bright': '#f8f9ff',
        'secondary-fixed-dim': '#4edea3',
        'inverse-primary': '#bec6e0',
        'on-primary-container': '#7c839b',
        outline: '#76777d',
        'on-background': '#0b1c30',
        warning: '#FF9800',
        harvest: '#9333ea',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', '2xl': '1rem', '3xl': '1.5rem', full: '9999px' },
      spacing: { gutter: '12px', xs: '4px', xl: '32px', 'safe-margin': '20px', md: '16px', sm: '8px', lg: '24px', base: '4px' },
      fontFamily: { sans: ['Be Vietnam Pro', 'sans-serif'] },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
